# This file configures the build and deployment settings for Netlify

[build]
  # The command to build your site (if you had a build step)
  # For a static site, we don't need a build command.
  
  # The directory that contains your built frontend.
  publish = "frontend/"
  
  # The directory where your serverless functions live.
  functions = "netlify/functions/"

# This rule redirects all API calls to your serverless function.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

